import type { Metadata } from "next";
import { Nunito, Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/app/AppProvider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Appsenin Next App",
  description: "Generated by FisherFLD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${inter.variable}`}
      > 
      <AppProvider>
        {children}
      </AppProvider>
      </body>
    </html>
  );
}
